# Generated by Django 4.2.2 on 2023-07-09 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
    ]
